### PR TITLE
Russian update

### PR DESCRIPTION
**Pull request by doktorjet**
Still in need of some tricky non-chemical abbreviations.

### CODE REVIEW

**Comment by sswelm** [comment]
I still see several resource descriptions are untranslated

**Comment by doktorjet** [comment]
Which ones? Some RF fuels were never used or produced in Russia, thus they never achieved approppriate russian names.
NGNC? It's "Нитроглицерин/Нитроцеллюлоза" - too long.
IntakeAtm? It's disputable, as most sane translation would be exact copy of IntakeAir - "Забортный воздух". Should players be able to differ those two resources? 
VacuumPlasma? I have no idea what modmaker had in mind. Vacuum is ABSENCE of material , while plasma is a form of material.

**Comment by sswelm** [comment]
LqdArgon is missing a translation

**Comment by sswelm** [comment]
To Translate Vacuum Plasma, perhaps you could use the [Ukane Page on Vacuum Plasma](url=https://uk.wikipedia.org/wiki/%D0%94%D0%B2%D0%B8%D0%B3%D1%83%D0%BD_%D0%BD%D0%B0_%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%96_%D0%BF%D0%BB%D0%B0%D0%B7%D0%BC%D0%B8_%D1%84%D1%96%D0%B7%D0%B8%D1%87%D0%BD%D0%BE%D0%B3%D0%BE_%D0%B2%D0%B0%D0%BA%D1%83%D1%83%D0%BC%D1%83).

**Comment by doktorjet** [comment]
Modern ukrainian 'mova' is 95% illegible. Ukrainian government worked hard for years, trying to kill all common slavic roots in language to achieve such an effect.
Give me an english link or a brief description, what that thing is. A quantum foam maybe? Some versions of KSPI used quantum foam IIRC. Though it's not something storeable. And either I can't imagine any kind of plasma STORED outside of TOKAMAK-like magnetic trap.

**Comment by doktorjet** [comment]
Nevermind. Found english text myself.
Proper name in english is "Quantum Vacuum", not "Vacuum Plasma". Latter is complete nonsense.
And it's a physical effect rather then a thing you can somehow store.

**Comment by sswelm** [comment]
Well in KDPI it exists simply as a way to make it function with KSP Engine Part module which needs a resource with mass to generate thrust. The resource itself is simply generated in a small buffer depending on expected requirements

**Comment by doktorjet** [comment]
//KSP Engine Part module which needs a resource with mass to generate thrust
Believe me, it DOES NOT require resource with mass. Thrust is just a Unity physical force vector, not related to the fuel "used". ISP only affects fuel mass delta per second and massless EC resource works for KSP engines pretty fine.

**Comment by sswelm** [comment]
Then how does it know how much resource to consume if the propellant is massless? the engine Isp is literally a mass to thrust conversion rate. The higher the Isp, they less mass is required to generate thrust, the lower the isp the more mass is required.

**Comment by sswelm** [comment]
I don't know what KSP engine current behaviour is be perhaps what might be possible is that KSP engine now counts massless resource of having a tiny mass.

**Comment by doktorjet** [comment]
Resources are counted in units. Units may have **any** mass per unit - even zero (like EC). Don't think of KSP resources as of real world reactive propellants. 
BTW real life EMdrive produces thrust in vacuum without any propellant - with electricity only.

**Pull request merged**
