### PR TITLE
Corrected localization and cost CompressedAir

### PR DESCRIPTION
**Pull request by sswelm**

### CODE REVIEW

**Comment by BobPalmer** [comment]
Advanced warning that CompressedAir is going to be removed as it conflicts with a prior mod, and is not in use by mods other than KSPIE from a CRP standpoint.  Suggest you update your own configs accordingly.  I  will leave it in place for this week's release to give you a bit of runway.

**Comment by sswelm** [comment]
From what I can tell it is no longer in conflict with any of @Angel-125 mods but the Fact that there was a conflict in the past means it is likely to conflict in the future when removed.

**Comment by BobPalmer** [comment]
Would need @Angel-125 to confirm that.

**Comment by BobPalmer** [comment]
No traction on this issue either, so I'll be defaulting to denying single-mod resources, starting with this one.  If you want to use this, and there's no interest in making it a shared resource (i.e. by more than one mod), then it will be removed after new years - this should give you time to include it in KSPI-E.  Prior resource will be grandfathered as there have been no public complaints lodged about them.

**Comment by sswelm** [comment]
Technically the resource is used by 2 mods, which happen to be both under my control.
Perhaps before taking any one-sided radical steps, you should first put in the discussion thread

**Pull request merged**
