### PR TITLE
Added ResourceConfig for Regolith

### PR DESCRIPTION
**Pull request by sswelm**
Regolith is an abstract resource, representing the top soil layer which has different chemical composition depending on its location

### CODE REVIEW

**Comment by BobPalmer** [comment]
This seems like the same thing as 'dirt' with similar distributions?  Not sure we need this many planetary resources that are essentially the same thing?

**Comment by sswelm** [comment]
Dirt can mean a large number of things

According to Wikipedia : Dirt is unclean matter, especially when in contact with a person's clothes, skin or possessions when they are said to become dirty. Common types of dirt include:

    dust — a general powder of organic or mineral matter
    filth — foul matter such as excrement
    grime — a black, ingrained dust such as soot
    soil — the mix of clay, sand, and humus which lies on top of bedrock

Regolith on the other hand is much more precise. According to wikipedia: Regolith is a layer of loose, heterogeneous superficial material covering solid rock. It includes dust, soil, broken rock, and other related materials and is present on Earth, the Moon, Mars, some asteroids, and other terrestrial planets and moons.

**Comment by BobPalmer** [comment]
Point remains though that I am starting to get complaints on the quantity of unused planetary resources in CRP, and it seems the purposes overlap, especially given you have it as a 100% resource, and it is a resource only used by one mod.

**Comment by sswelm** [comment]
Well in this case it abstract resource which represent a property rather a specific chemical substance, Besides that it has also educational value. Dirt will simply not do.

**Comment by sswelm** [comment]
I removed the global specification, it will now only be applied to specific celestial bodies

**Pull request closed without merging**
